### ISSUE TITLE
Client methods are generated with mandatory parameters instead of varargs when default values are specified in the spec

### ISSUE THREAD

**Issue by vdayanand** [JuliaComputing/OpenAPI.jl#87]
Example:

spec
```
paths:
  /example:
    get:
      parameters:
        - name: limit
          in: query
          required: true
          schema:
            type: integer
            default: 10
```
Generated:
```
function get_example(limit::Int)
    # Call API...
end
```
Expected:
```
function get_example(limit::Int=10)
    # Call API...
end
```
